const categoryPlan=[{id:"all",label:"All Jewellery"},{id:"bridal",label:"Bridal Collection"},{id:"brass-copper",label:"Brass & Copper"},{id:"temple",label:"Temple Jewellery"},{id:"gold-plated",label:"Gold-Plated Edit"},{id:"rajasthani",label:"Rajasthani Heritage"},{id:"daily-wear",label:"Daily Wear"}];
const products=[
{id:1,name:"Rajputi Rani Haar",category:"rajasthani",tag:"Rajasthani",price:3499,image:"https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=80",description:"A regal layered haar inspired by Rajasthan's bridal artistry.",rating:5},
{id:2,name:"Antique Brass Choker",category:"brass-copper",tag:"Brass & Copper",price:1899,image:"https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80",description:"Antique-finish statement choker for festive and everyday styling.",rating:4},
{id:3,name:"Temple Lakshmi Necklace",category:"temple",tag:"Temple",price:2699,image:"https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=900&q=80",description:"Traditional temple-inspired necklace with heritage detailing.",rating:5},
{id:4,name:"Lightweight Gold-Look Set",category:"gold-plated",tag:"1–2 Gram Gold-Plated",price:1299,image:"https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=900&q=80",description:"Elegant lightweight jewellery designed for ready-stock gifting.",rating:4},
{id:5,name:"Kundan Bridal Jhumkas",category:"bridal",tag:"Bridal",price:1599,image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",description:"Kundan jhumkas with a rich bridal finish and pearl accents.",rating:5},
{id:6,name:"Meenakari Hathphool",category:"rajasthani",tag:"Rajasthani",price:999,image:"https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80",description:"Colourful meenakari hathphool for weddings and celebrations.",rating:4},
{id:7,name:"Daily-Wear Mangalsutra",category:"daily-wear",tag:"Daily Wear",price:1199,image:"https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80",description:"A graceful, comfortable mangalsutra for daily wear.",rating:5},
{id:8,name:"Antique Kamarband",category:"brass-copper",tag:"Brass & Copper",price:2299,image:"https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=80",description:"Ornate antique kamarband designed for traditional occasions.",rating:4},
{id:9,name:"Gold-Look Bangle Pair",category:"gold-plated",tag:"1–2 Gram Gold-Plated",price:799,image:"https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=900&q=80",description:"Ready-stock bangles available in sizes 2x4, 2x6, 2x8 and 2x10.",rating:4},
{id:10,name:"Temple Jadau Pendant",category:"temple",tag:"Temple",price:899,image:"https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80",description:"A compact pendant for adding a sacred heritage touch.",rating:5},
{id:11,name:"Rajasthani Borla Maang Tikka",category:"bridal",tag:"Bridal",price:1099,image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",description:"Classic borla-style maang tikka for bridal and festive looks.",rating:5},
{id:12,name:"Antique Earrings & Bali Set",category:"daily-wear",tag:"Daily Wear",price:649,image:"https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80",description:"Versatile antique earrings and bali set for everyday elegance.",rating:4}];
const productGrid=document.getElementById("product-grid"),cartItems=document.getElementById("cartItems"),cartCount=document.getElementById("cart-count"),cartTotal=document.getElementById("cartTotal"),cartDrawer=document.getElementById("cartDrawer"),checkoutModal=document.getElementById("checkoutModal");let cart=[],activeFilter="all";
function currency(value){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value)}
function renderProducts(){const query=(document.getElementById("searchInput")?.value||"").toLowerCase();const list=products.filter(p=>(activeFilter==="all"||p.category===activeFilter)&&(!query||`${p.name} ${p.tag} ${p.description}`.toLowerCase().includes(query)));productGrid.innerHTML=list.length?list.map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="product-content"><div class="product-meta"><span class="product-tag">${p.tag}</span><span class="rating">${"★".repeat(p.rating)}${"☆".repeat(5-p.rating)}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="product-row"><span class="price">${currency(p.price)}</span><button class="product-btn" data-id="${p.id}">Add to bag</button></div></div></article>`).join(""):"<p class=\"empty-results\">No jewellery pieces match your search.</p>";document.querySelectorAll(".product-btn").forEach(b=>b.addEventListener("click",()=>addToCart(Number(b.dataset.id))))}
function updateCart(){cartCount.textContent=cart.reduce((s,i)=>s+i.quantity,0);cartTotal.textContent=currency(cart.reduce((s,i)=>s+i.price*i.quantity,0));cartItems.innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><img src="${i.image}" alt="${i.name}"><div><h4>${i.name}</h4><p>Quantity: ${i.quantity}</p></div><strong class="price-tag">${currency(i.price*i.quantity)}</strong></div>`).join(""):"<p class=\"empty-cart\">Your bag is waiting for something beautiful.</p>"}
function addToCart(id){const product=products.find(p=>p.id===id),existing=cart.find(p=>p.id===id);if(existing)existing.quantity++;else if(product)cart.push({...product,quantity:1});updateCart();cartDrawer.classList.add("open")}
function chooseCategory(filter){activeFilter=filter;document.querySelectorAll(".filter-btn").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));renderProducts();document.getElementById("featured")?.scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".filter-btn").forEach(b=>b.addEventListener("click",()=>chooseCategory(b.dataset.filter)));
document.querySelectorAll("[data-filter-link]").forEach(a=>a.addEventListener("click",()=>chooseCategory(a.dataset.filterLink)));
document.querySelector(".dropdown-trigger").addEventListener("click",e=>{const parent=e.currentTarget.closest(".nav-dropdown");parent.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",parent.classList.contains("open"))});
document.querySelector(".mobile-menu").addEventListener("click",e=>{const nav=document.querySelector(".main-nav"),open=nav.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",open)});
document.querySelector(".search-toggle").addEventListener("click",()=>{const panel=document.getElementById("searchPanel");panel.classList.toggle("open");if(panel.classList.contains("open"))document.getElementById("searchInput").focus()});document.getElementById("searchInput").addEventListener("input",renderProducts);
document.querySelector(".cart-toggle").addEventListener("click",()=>cartDrawer.classList.toggle("open"));document.querySelector(".close-cart").addEventListener("click",()=>cartDrawer.classList.remove("open"));document.querySelector(".checkout-btn").addEventListener("click",()=>{if(!cart.length)return alert("Please add a jewellery piece before placing an order.");cartDrawer.classList.remove("open");checkoutModal.classList.add("open")});document.querySelector(".close-modal").addEventListener("click",()=>checkoutModal.classList.remove("open"));document.getElementById("checkoutForm").addEventListener("submit",e=>{e.preventDefault();alert("Thank you! We will contact you on WhatsApp to confirm your jewellery order.");checkoutModal.classList.remove("open");cart=[];updateCart()});document.querySelector(".newsletter-form").addEventListener("submit",e=>{e.preventDefault();alert("You are now subscribed to Vimla Designer Jewellery updates.");e.target.reset()});renderProducts();updateCart();
